// Each palette is a flat set of color tokens used across every screen.
// Add a new theme by adding an entry here — nothing else needs to change
// structurally since screens only ever reference these token names.
export const PALETTES = {
  light: {
    label: 'Light',
    isDark: false,
    background: '#F5F6FA',
    surface: '#FFFFFF',
    primary: '#3B82F6',
    primaryLight: '#EEF2FF',
    text: '#111111',
    textSecondary: '#666666',
    border: '#DDDDDD',
    danger: '#EF4444',
    dangerLight: '#FEE2E2',
    success: '#10B981',
    statusBarStyle: 'dark',
  },
  pink: {
    label: 'Pink',
    isDark: false,
    background: '#FFF0F5',
    surface: '#FFFFFF',
    primary: '#EC4899',
    primaryLight: '#FCE7F3',
    text: '#4A044E',
    textSecondary: '#A64D79',
    border: '#F3C6DC',
    danger: '#E11D48',
    dangerLight: '#FCE4E9',
    success: '#10B981',
    statusBarStyle: 'dark',
  },
  darkBlue: {
    label: 'Dark — Blue',
    isDark: true,
    background: '#0F172A',
    surface: '#1E293B',
    primary: '#60A5FA',
    primaryLight: '#1E3A5F',
    text: '#F1F5F9',
    textSecondary: '#94A3B8',
    border: '#334155',
    danger: '#F87171',
    dangerLight: '#3F1D2E',
    success: '#34D399',
    statusBarStyle: 'light',
  },
  darkGray: {
    label: 'Dark — Gray',
    isDark: true,
    background: '#1F2937',
    surface: '#374151',
    primary: '#2DD4BF',
    primaryLight: '#134E4A',
    text: '#F9FAFB',
    textSecondary: '#9CA3AF',
    border: '#4B5563',
    danger: '#F87171',
    dangerLight: '#3F1D2E',
    success: '#34D399',
    statusBarStyle: 'light',
  },
  darkBlack: {
    label: 'Dark — Black',
    isDark: true,
    background: '#000000',
    surface: '#121212',
    primary: '#F59E0B',
    primaryLight: '#3A2E10',
    text: '#FFFFFF',
    textSecondary: '#A1A1AA',
    border: '#27272A',
    danger: '#F87171',
    dangerLight: '#3F1D2E',
    success: '#34D399',
    statusBarStyle: 'light',
  },
};

export const DEFAULT_THEME = 'light';
