// Each palette is a flat set of color tokens used across every screen.
// Add a new theme by adding an entry here — nothing else needs to change
// structurally since screens only ever reference these token names.
export const PALETTES = {
  light: {
    label: 'Light',
    isDark: false,
    background: '#F5F6FA',
    surface: '#FFFFFF',
    primary: '#3B82F6',
    primaryLight: '#EEF2FF',
    text: '#111111',
    textSecondary: '#666666',
    border: '#DDDDDD',
    danger: '#EF4444',
    dangerLight: '#FEE2E2',
    success: '#10B981',
    statusBarStyle: 'dark',
  },
  pink: {
    label: 'Pink',
    isDark: false,
    background: '#FFF0F5',
    surface: '#FFFFFF',
    primary: '#EC4899',
    primaryLight: '#FCE7F3',
    text: '#4A044E',
    textSecondary: '#A64D79',
    border: '#F3C6DC',
    danger: '#E11D48',
    dangerLight: '#FCE4E9',
    success: '#10B981',
    statusBarStyle: 'dark',
  },
  darkBlue: {
    label: 'Dark — Blue',
    isDark: true,
    background: '#0F172A',
    surface: '#1E293B',
    primary: '#60A5FA',
    primaryLight: '#1E3A5F',
    text: '#F1F5F9',
    textSecondary: '#94A3B8',
    border: '#334155',
    danger: '#F87171',
    dangerLight: '#3F1D2E',
    success: '#34D399',
    statusBarStyle: 'light',
  },
  darkGray: {
    label: 'Dark — Gray',
    isDark: true,
    background: '#1F2937',
    surface: '#374151',
    primary: '#2DD4BF',
    primaryLight: '#134E4A',
    text: '#F9FAFB',
    textSecondary: '#9CA3AF',
    border: '#4B5563',
    danger: '#F87171',
    dangerLight: '#3F1D2E',
    success: '#34D399',
    statusBarStyle: 'light',
  },
  darkBlack: {
    label: 'Dark — Black',
    isDark: true,
    background: '#000000',
    surface: '#121212',
    primary: '#F59E0B',
    primaryLight: '#3A2E10',
    text: '#FFFFFF',
    textSecondary: '#A1A1AA',
    border: '#27272A',
    danger: '#F87171',
    dangerLight: '#3F1D2E',
    success: '#34D399',
    statusBarStyle: 'light',
  },

  // Pond — the palette the redesign is built on. Deep still water for the
  // brand, a warm sand ground instead of a grey one, and one warm accent kept
  // for moments rather than spent on every button.
  //
  // Added alongside the old themes rather than replacing them: switching to it
  // is how the new colours get judged on a real screen, with real amounts, in
  // real light, before any screen is redrawn.
  pondLight: {
    label: 'Pond',
    isDark: false,
    background: '#F4F2EC',
    surface: '#FFFFFF',
    primary: '#0E7C66',
    primaryLight: '#D7EDE6',
    text: '#14201C',
    textSecondary: '#5C6B65',
    border: '#E4E0D6',
    danger: '#A6432A',
    dangerLight: '#FDF3F0',
    success: '#0E7C66',
    statusBarStyle: 'dark',
  },
  pondDark: {
    label: 'Pond — night',
    isDark: true,
    background: '#0E1512',
    surface: '#16201C',
    primary: '#3DBE9B',
    primaryLight: '#15322A',
    text: '#EDF2EF',
    textSecondary: '#94A79E',
    border: '#27332E',
    danger: '#F0907A',
    dangerLight: '#3A201A',
    success: '#3DBE9B',
    statusBarStyle: 'light',
  },
};

export const DEFAULT_THEME = 'light';
